m1 = matrix(1:12,ncol=4,nrow=3)
print("4 X 3 matrix:")
print(m1)
cells = c(19,21,23,24)
rnames = c("Row1", "Row2")
cnames = c("Col1", "Col2")
m2 = matrix(cells, nrow=2, ncol=2, byrow=TRUE, dimnames=list(rnames, cnames))
print("2 × 2 matrix with labels, filled by rows: ")
print(m2)
print("2 x 2 matrix with labels, filled by columns: ")
m3 = matrix(cells, nrow=2, ncol=2, byrow=FALSE, dimnames=list(rnames, cnames))
print(m3)
